### PR TITLE
create customRoute to include layout components

### PR DESCRIPTION
**Pull request by aurelienroux**
create a customRoute components to include header and footer comp directly and clean up AppRouter.

### CODE REVIEW

**Comment by fuentesloic** [comment]
> create a customRoute components to include header and footer comp directly and clean up AppRouter.

LGTM! 👍 now, we are overkill 😜 and to keep this "overkill-itude", I just made 2 useless PR 🤓

**Comment by fuentesloic** [comment]
Oh and reall question @aurelienroux, why using  `AppRouter from './routes/AppRouter'`and not ` App from './router(s?)/App';`

**Comment by fuentesloic** [comment]
Also `routes` seems more a list or something like that than a real component with logical inside, you see what I mean?

**Comment by aurelienroux** [comment]
> Oh and reall question @aurelienroux, why using AppRouter from './routes/AppRouter'and not App from './router(s?)/App';

guess it came from the habit of having an App file in folder root as an entry point for the application, but yeah I agree it's not logical since I named the entrypoint as index.js. 😄

**Pull request merged**
